### ISSUE TITLE
METAR with no TAF

### ISSUE THREAD

**Issue by moto501** [avwx-rest/avwx-engine#28]
Hi, when retrieving a METAR for AU BOM station YCNK, there is no TAF issued as this is not an airport with a published approach. Hence there is only a METAR. How can we retrieve just the metar data only when no TAF exists? I see from service.py that the BOM service looks for TAF to then pull the METAR data. Can this dig a bit deeper?

**Comment by flyinactor91** [comment]
Thanks for letting me know. I've fixed this in the last commit. It's part of an alpha feature release (1.4.0a1) which is now on PyPI. Let me know if it's working for you.

**Comment by moto501** [comment]
pulled and installed the updated version: Successfully installed avwx-engine-1.4.0a1

However, when running:

    from avwx.station import Station
  File "/home/pi/.local/lib/python3.7/site-packages/avwx/__init__.py", line 5, in <module>
    from avwx.current.metar import Metar
ModuleNotFoundError: No module named 'avwx.current'

**Comment by flyinactor91** [comment]
I'm having tons of module import issues right now. I went from a flat structure to submodules, and these import errors are only showing up while installed in a separate environment. Working on fixing while trying to keep everything as similar as possible with the primary imports.

**Comment by flyinactor91** [comment]
The import issue should be fixed with 1.4.0a9 Give that a try.

**Comment by moto501** [comment]
Yes fixed 😊 Thanks Michael

Regards,
Evan Rose
0411130975
0284466711
evrose@cisco.com
