### ISSUE TITLE
Print METAR to webhook

### ISSUE THREAD

**Issue by H4rryTheDev** [avwx-rest/avwx-engine#36]
Hiya!

Not really an issue, more of a query.

Could I use my API key to print a METAR to a Discord webhook daily?

**Comment by flyinactor91** [comment]
Yes. Discord bots are a popular use case. See AvBot for an example:

https://top.gg/bot/494888240617095168

**Comment by H4rryTheDev** [comment]
Hiya, 

If i were to do this, how would I do it lol?

I just need it to print 1 METAR

**Comment by flyinactor91** [comment]
I haven't made a Discord bot myself, but I have done some Slack bots. You'd need your own backend server for the bot's commands to go to. That server would make the call to AVWX (or use this library :) if you use Python) and return the report to the Discord bot.

You may be able to make it with no code using a tool like https://botghost.com but it depends on their feature set.

Hope that helps!
