### ISSUE TITLE
Error scrapper

### ISSUE THREAD

**Issue by matirojasg** [avwx-rest/avwx-engine#60]
Hello, I have the following error using the TAF Scrapper: NOAA_Scrape server returned 404. Is it an error of the library?

**Comment by matirojasg** [comment]
It seems that AWC changed its page, and that could affect the URLs that you request or not? https://aviationweather.gov/

**Comment by matirojasg** [comment]
https://aviationweather.gov/data/api/#/

**Comment by matirojasg** [comment]
could you fix it?

**Comment by flyinactor91** [comment]
A fix for the scrape class should be pushed later tonight. A quick fix has been pushed re-mapping the `NOAA` service alias to `NOAA_FTP` among other fixes. See if updating to 1.8.20 fixes your immediate issue.

**Comment by flyinactor91** [comment]
Pushed 1.8.21 which updates the scrape classes to pull from the v3 scrape sources.
